apiVersion: v1
kind: Service
metadata:
    name: flask-app-service
spec:
    type: {{ .Values.service.type }}
    selector:
        app: flask-app
    ports:
      - port: {{ .Values.service.port }}
        targetPort: {{ .Values.containerPort }}

